# Generated by Django 4.1.5 on 2023-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
